# Generated by Django 5.0.1 on 2024-02-25 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wins',
        ),
    ]
