# Generated by Django 5.0.1 on 2024-02-08 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='watch_list',
            new_name='watchlist',
        ),
    ]
