# Generated by Django 5.0.1 on 2024-02-08 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_watch_list_user_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='watchlist',
            new_name='watch_list',
        ),
    ]
