# Generated by Django 5.0.1 on 2024-02-08 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_rename_watchlist_user_watch_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='watch_list',
            new_name='watchlist',
        ),
    ]
