# Generated by Django 5.0.1 on 2024-02-12 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_rename_current_amount_bid_current_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='current_bid',
            new_name='bid_amount',
        ),
    ]
