# Generated by Django 5.0.1 on 2024-02-13 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_bid_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid_amount',
            new_name='current_bid',
        ),
    ]
