# Generated by Django 5.0.1 on 2024-02-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_listing_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='winner',
            field=models.CharField(default=None, max_length=45),
            preserve_default=False,
        ),
    ]
