# Generated by Django 5.0.1 on 2024-02-24 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_remove_listing_winner_user_winner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='winner',
        ),
        migrations.AddField(
            model_name='user',
            name='wins',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
