# Generated by Django 5.0.2 on 2024-04-07 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='posts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to='network.post'),
        ),
    ]
