# Generated by Django 5.0.2 on 2024-04-15 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_user_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='posts',
        ),
    ]
