# Generated by Django 5.0.2 on 2024-05-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_user_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.CharField(blank=True, max_length=42),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.CharField(blank=True, max_length=42),
        ),
    ]
