# Generated by Django 5.0.2 on 2024-06-28 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_comments_texingt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='texingt',
            new_name='texing',
        ),
    ]
