# Generated by Django 5.0.2 on 2024-06-28 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_rename_texingt_comments_texing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='texing',
        ),
    ]
