# Generated by Django 5.0.2 on 2024-06-28 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_remove_comments_texing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comments',
        ),
    ]
