# Generated by Django 5.0.2 on 2024-06-28 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
